name: ludus
favicon: null
layout_spectrum: 0.892135730246082
typography_spectrum: 0.19827008084394038
title: Ludus
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6585716172121465
  lightness: 0.8957482622936368
  saturation: 0.25439405418001115
  rhythmicContrast: 0.43575793923810124
purpose: []
