name: ludus
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Ludus
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#888282'
    - '#656368'
    - '#3e2101'
    - '#b14336'
    - '#c5825e'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
